name: thai_herbal_gacp
description: Flutter application for Thai Herbal GACP Platform

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  http: ^1.1.0
  dio: ^5.3.3
  flutter_hooks: ^0.20.0
  equatable: ^2.0.5
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  path_provider: ^2.0.15
  path: ^1.8.3
  file_picker: ^6.1.1
  open_file: ^3.3.3
  share_plus: ^7.0.1
  flutter_svg: ^2.0.7
  qr_flutter: ^4.2.0
  printing: ^5.11.0
  cached_network_image: ^3.3.0
  flutter_form_builder: ^8.1.0
  form_builder_validators: ^8.0.0
  url_launcher: ^6.2.0
  flutter_dotenv: ^5.1.0
  connectivity_plus: ^5.0.0
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  uuid: ^3.0.7
  flutter_secure_storage: ^8.0.0
  permission_handler: ^10.4.4
  pdf: ^3.10.4
  image: ^4.1.4
  syncfusion_flutter_pdf: ^23.1.44

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.3
  mockito: ^5.4.2
  lint: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/certificates/
    - .env
