name: thai_herbal_gacp_event_ledger
description: Event sourcing and digital signature components for GACP
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  postgres: ^2.6.0
  uuid: ^3.0.7
  encrypt: ^5.0.1
  pointycastle: ^3.7.3
  x509: ^0.2.0
  asn1lib: ^1.0.0
  collection: ^1.17.2
  crypto: ^3.0.3
  json_annotation: ^4.8.1
  thai_herbal_gacp_models:
    path: ../thai_herbal_gacp_models

dev_dependencies:
  build_runner: ^2.4.5
  json_serializable: ^6.7.1
  lints: ^2.1.1
  test: ^1.24.0
