name: thai_herbal_gacp
description: 🌿 Thai Herbal GACP Platform - Mobile Application for GACP Certification

# ===================================================================
# Application Information
# ===================================================================
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0+30000

# ===================================================================
# Environment Configuration
# ===================================================================
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

# ===================================================================
# Dependencies
# ===================================================================
dependencies:
  flutter:
    sdk: flutter

  # ===================================================================
  # UI & Widgets
  # ===================================================================
  
  # Material Design
  material_color_utilities: ^0.5.0
  
  # Icons
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  icons_launcher: ^2.1.3
  
  # Animations
  lottie: ^2.6.0
  flutter_animate: ^4.2.0+1
  shimmer: ^3.0.0
  
  # UI Components
  flutter_screenutil: ^5.9.0
  gap: ^3.0.1
  easy_refresh: ^3.3.4
  flutter_staggered_grid_view: ^0.7.0
  smooth_page_indicator: ^1.1.0
  flutter_speed_dial: ^7.0.0
  
  # ===================================================================
  # State Management
  # ===================================================================
  
  # BLoC Pattern
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  
  # Reactive Programming
  rxdart: ^0.27.7
  
  # ===================================================================
  # Navigation & Routing
  # ===================================================================
  
  go_router: ^10.1.2
  auto_route: ^7.7.1
  
  # ===================================================================
  # Network & API
  # ===================================================================
  
  # HTTP Client
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Network Info
  connectivity_plus: ^4.0.2
  internet_connection_checker: ^1.0.0+1
  
  # WebSocket
  web_socket_channel: ^2.4.0
  
  # ===================================================================
  # Local Storage & Database
  # ===================================================================
  
  # Key-Value Storage
  shared_preferences: ^2.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Secure Storage
  flutter_secure_storage: ^9.0.0
  
  # SQLite Database
  sqflite: ^2.3.0
  floor: ^1.4.2
  
  # ===================================================================
  # Authentication & Security
  # ===================================================================
  
  # JWT & OAuth
  jwt_decoder: ^2.0.1
  oauth2: ^2.0.2
  
  # Biometric Authentication
  local_auth: ^2.1.6
  
  # Encryption
  crypto: ^3.0.3
  encrypt: ^5.0.1
  
  # ===================================================================
  # Media & Files
  # ===================================================================
  
  # Camera & Gallery
  image_picker: ^1.0.4
  camera: ^0.10.5+4
  
  # Image Processing
  image: ^4.1.3
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  
  # File Handling
  file_picker: ^5.5.0
  path_provider: ^2.1.1
  open_filex: ^4.3.2
  
  # PDF Generation
  pdf: ^3.10.4
  printing: ^5.11.0
  
  # ===================================================================
  # Location & Maps
  # ===================================================================
  
  # Location Services
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Maps
  google_maps_flutter: ^2.5.0
  flutter_map: ^6.0.1
  
  # ===================================================================
  # Sensors & Hardware
  # ===================================================================
  
  # QR Code
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  
  # Device Info
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0
  
  # Permissions
  permission_handler: ^11.0.1
  
  # ===================================================================
  # Notifications & Messaging
  # ===================================================================
  
  # Push Notifications
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  firebase_analytics: ^10.4.6
  
  # Local Notifications
  flutter_local_notifications: ^15.1.1
  
  # ===================================================================
  # Internationalization
  # ===================================================================
  
  # Multi-language Support
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  easy_localization: ^3.0.3
  
  # ===================================================================
  # Utils & Tools
  # ===================================================================
  
  # Date & Time
  jiffy: ^6.2.1
  
  # Logging
  logger: ^2.0.2+1
  
  # Environment Configuration
  flutter_dotenv: ^5.1.0
  
  # Utilities
  uuid: ^4.0.0
  collection: ^1.18.0
  
  # Validation
  form_validator: ^2.1.1
  email_validator: ^2.1.17
  
  # ===================================================================
  # Chart & Analytics
  # ===================================================================
  
  # Charts
  fl_chart: ^0.63.0
  syncfusion_flutter_charts: ^23.1.36
  
  # ===================================================================
  # AI & ML
  # ===================================================================
  
  # TensorFlow Lite
  tflite_flutter: ^0.10.4
  
  # ===================================================================
  # Development Dependencies
  # ===================================================================
dev_dependencies:
  flutter_test:
    sdk: flutter

  # ===================================================================
  # Linting & Code Quality
  # ===================================================================
  
  flutter_lints: ^2.0.3
  very_good_analysis: ^5.1.0
  
  # ===================================================================
  # Code Generation
  # ===================================================================
  
  # Build Runner
  build_runner: ^2.4.6
  
  # JSON Serialization
  json_serializable: ^6.7.1
  
  # Auto Route Generation
  auto_route_generator: ^7.2.0
  
  # Retrofit Generation
  retrofit_generator: ^8.0.4
  
  # Hive Generation
  hive_generator: ^2.0.1
  
  # Floor Generation
  floor_generator: ^1.4.2
  
  # Mock Generation
  mockito: ^5.4.2
  
  # ===================================================================
  # Testing
  # ===================================================================
  
  # Unit Testing
  test: ^1.24.6
  
  # Widget Testing
  flutter_test:
    sdk: flutter
  
  # Integration Testing
  integration_test:
    sdk: flutter
  
  # Mock Data
  faker: ^2.1.0
  
  # Network Mocking
  http_mock_adapter: ^0.4.4
  
  # BLoC Testing
  bloc_test: ^9.1.4
  
  # ===================================================================
  # Performance & Monitoring
  # ===================================================================
  
  # Crashlytics
  firebase_crashlytics: ^3.3.6
  
  # Performance Monitoring
  firebase_performance: ^0.9.2+6

# ===================================================================
# Flutter Configuration
# ===================================================================
flutter:
  
  # Enable Material Design
  uses-material-design: true
  
  # Enable generate flag
  generate: true

  # ===================================================================
  # Assets Configuration
  # ===================================================================
  assets:
    # Images
    - assets/images/
    - assets/images/herbs/
    - assets/images/icons/
    - assets/images/logos/
    - assets/images/backgrounds/
    - assets/images/illustrations/
    
    # Animations
    - assets/animations/
    - assets/lottie/
    
    # Fonts
    - assets/fonts/
    
    # Data Files
    - assets/data/
    - assets/json/
    
    # Localization
    - assets/translations/
    
    # Mock Data (Development Only)
    - assets/mock/

  # ===================================================================
  # Fonts Configuration
  # ===================================================================
  fonts:
    # Primary Font - Kanit (Thai-friendly)
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Light.ttf
          weight: 300
        - asset: assets/fonts/Kanit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Kanit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Kanit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Kanit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Kanit-ExtraBold.ttf
          weight: 800
    
    # Secondary Font - Prompt (Thai-friendly)
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Light.ttf
          weight: 300
        - asset: assets/fonts/Prompt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Prompt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Prompt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Prompt-Bold.ttf
          weight: 700
    
    # Icon Font
    - family: HerbIcons
      fonts:
        - asset: assets/fonts/HerbIcons.ttf

# ===================================================================
# Platform-specific Configuration
# ===================================================================

# Android Configuration
# Configure in android/app/build.gradle and android/app/src/main/AndroidManifest.xml

# iOS Configuration  
# Configure in ios/Runner/Info.plist and ios/Runner.xcodeproj

# ===================================================================
# Flutter Inspector Configuration
# ===================================================================
flutter_intl:
  enabled: true
  class_name: S
  main_locale: th
  arb_dir: lib/l10n
  output_dir: lib/generated

# ===================================================================
# Dart Analysis Configuration
# ===================================================================
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "build/**"
    - "lib/generated/**"
  
  plugins:
    - custom_lint

# ===================================================================
# Custom Lint Rules
# ===================================================================
custom_lint:
  rules:
    - avoid_print: true
    - prefer_const_constructors: true
    - prefer_const_literals_to_create_immutables: true
    - use_build_context_synchronously: true

# ===================================================================
# Build Configuration
# ===================================================================

# Web Configuration
flutter:
  web:
    compilation-mode: release
    
# Desktop Configuration  
flutter:
