name: thai_herbal_gacp_government_integration
description: Thai government integration components for GACP
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.3.3
  json_annotation: ^4.8.1
  thai_herbal_gacp_models:
    path: ../thai_herbal_gacp_models
  thai_herbal_gacp_event_ledger:
    path: ../thai_herbal_gacp_event_ledger

dev_dependencies:
  build_runner: ^2.4.5
  json_serializable: ^6.7.1
  lints: ^2.1.1
  test: ^1.24.0
